### ISSUE TITLE
inf and NaNs for log-ratio & median difference in metasims 

### ISSUE THREAD

**Issue by softloud** [softloud/metasim#27]
## notes

- affects difference of medians, and log-ratios, but not medians
- confidence interval lower bounds -inf
- bias 

## task

- [ ] How are effects calculated?
- [ ] Is it possible that negative numbers are in there?
- [ ] Is it possible dividing by 0?

**Comment by softloud** [comment]
Dividing by zero!
