### ISSUE TITLE
poster for ESH2

### ISSUE THREAD

**Issue by softloud** [softloud/metasim#54]
## tasks

- [x] install `pagedown::`
- [x] install `Cairo::`
- [x] install `posterdown::`
- [ ] type up derivations
- [ ] tidy up failed experiment files
- [ ] demonstrate basic functionality
- [ ] describe the problem
- [ ] describe the solution 
- [ ] describe the maths
- [ ] why is simulating data a bitch?

## resources

Looks like `posterdown::` might be the way to go. 

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">Baby academia question. What is the purpose of a poster? <a href="https://twitter.com/emilyandthelime?ref_src=twsrc%5Etfw">@emilyandthelime</a> <a href="https://twitter.com/lingtax?ref_src=twsrc%5Etfw">@lingtax</a> <a href="https://twitter.com/adamhsparks?ref_src=twsrc%5Etfw">@adamhsparks</a> <br><br>Some work is almost done, and there&#39;s a call for who wants to present posters at ESH2 in a few weeks. I&#39;m all for motivational deadlines, not sure what I&#39;d be committing to.</p>&mdash; Charles T. Gray (@cantabile) <a href="https://twitter.com/cantabile/status/1110367135115534336?ref_src=twsrc%5Etfw">March 26, 2019</a></blockquote>
