### ISSUE TITLE
singletrial component

### ISSUE THREAD

**Issue by softloud** [softloud/metasim#61]
## objective

`metasims` should run on any appropriate `trial_fn` component.

## tasks

- [ ] get new error message
 - [ ] write tests for singletrial 
- [x] investigate sample size data shape in `metasims`

## help?! 

if you have time, @adamhsparks, @kylehamilton, @adam-gruer?

**Comment by softloud** [comment]
``` r
library(metasim)

test_metatrial <- metasims(trial_fn = metatrial, probar = FALSE)
test_singletrial <- metasims(trial_fn = singletrial, probar = FALSE)
#> Error: Column `measure` is unknown
```

Created on 2019-04-19 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by softloud** [comment]
``` r
library(metasim)

# single study trial component failing in metasims
metasims(single_study = TRUE, probar = FALSE, trial_fn = singletrial)
#> Error: Column `measure` is unknown

# default trial function
metasims(probar = FALSE, trial_fn = metatrial)
#> # A tibble: 216 x 16
#>        k tau2_true median_ratio  prop rdist parameters n     id   
#>    <dbl>     <dbl>        <dbl> <dbl> <chr> <list>     <lis> <chr>
#>  1     3         0            1   0.3 norm  <list [2]> <tib… sim_1
#>  2     3         0            1   0.3 norm  <list [2]> <tib… sim_1
#>  3     3         0            1   0.3 exp   <list [1]> <tib… sim_2
#>  4     3         0            1   0.3 exp   <list [1]> <tib… sim_2
#>  5     3         0            1   0.3 pare… <list [2]> <tib… sim_3
#>  6     3         0            1   0.3 pare… <list [2]> <tib… sim_3
#>  7     3         0            1   0.3 pare… <list [2]> <tib… sim_4
#>  8     3         0            1   0.3 pare… <list [2]> <tib… sim_4
#>  9     3         0            1   0.3 pare… <list [2]> <tib… sim_5
#> 10     3         0            1   0.3 pare… <list [2]> <tib… sim_5
#> # … with 206 more rows, and 8 more variables: true_effect <dbl>,
#> #   measure <chr>, tau_sq <dbl>, ci_width <dbl>, bias <dbl>,
#> #   coverage_count <int>, successful_trials <int>, coverage <dbl>
```

Created on 2019-04-19 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by softloud** [comment]
:thinking: I wonder if is this to do with how the sample sizes are generated again.

**Comment by softloud** [comment]
Nope. Both generated by `sim_n`.

**Comment by softloud** [comment]
Alas, no, we need those `...` to pass the simulation parameters to `trial_fn`. :thinking: but it does highlight where the problem occurs, so progress.

**Comment by adamhsparks** [comment]
Sorry, I suspected as much.
